server:
  port: 8050 # 项目请求端口
  servlet:
    context-path: /uc # 添加项目名称
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      name: uc
      url: jdbc:mysql://localhost:3386/user_center?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  # activiti config
  activiti:
    check-process-definitions: false # 自动检查、部署流程文件
    database-schema-update: true # 自动更新数据库结构
    history-level: full # 保存历史数据 none：不保留，activity：只保存流程实例和流程行为，audit：包括activity外还保留全部的流程任务极其属性，full：最高级别
    db-history-used: true # 使用历史表，false：只建立17张表
    #    process-definition-location-suffixes: 流程文件格式，默认支持 .bpmn20.xml 和 .bpmn
    #    process-definition-location-prefix: classpath/processes 指定流程文件存放目录，默认在resource下创建processes
logging:
  level:
    org.springframework: error
    org.apache: error
    com.alibaba: error
    springfox: error
    com.sxkj: debug
